Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0be2609ba883822ec
      Tags: 
        - Key: Name
          Value: !Join [" " , ["webserver", "01"]]
      SecurityGroups:
        - !Ref MySecurtyGroup
  
  MySecurtyGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH Connection via port 22"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0